name: Pipeline CI/CD

on:
  push:
    branches:
      - main
      - 'refs/heads/*'
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/fastapi-route53

jobs:
  build_and_push:
    runs-on: self-hosted

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Instalar Buildah e QEMU
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y buildah qemu-user-static

      - name: Configurar QEMU para multiplataforma
        run: |
          sudo update-binfmts --enable
          sudo update-binfmts --display

      - name: Construir e enviar imagem Docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          buildah login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          buildah bud -t ${{ env.DOCKER_IMAGE_NAME }}:latest .
          buildah push ${{ env.DOCKER_IMAGE_NAME }}:latest
